const SAVE_KEY = "cyberClashComplexSaveV2";
const TICK_MS = 1000;
const BOT_COUNT = 500;

const defaultState = {
  energy: 0,
  credits: 0,
  level: 1,
  xp: 0,
  xpNeeded: 100,
  rebirths: 0,
  prestige: 0,
  multiplier: 1,
  drones: 0,
  totalClicks: 0,
  heat: 0,
  stability: 100,
  cores: 1,
  packets: 0,
  currentTab: "upgrades",
  activeOperationId: null,
  operationProgress: 0,
  operationCompletions: {},
  upgradeLevels: {},
  research: {},
  achievements: [],
  eventLog: [],
  market: {
    creditValue: 1,
    volatility: 0.06,
    phase: "calm"
  }
};

let state = structuredClone(defaultState);
let bots = [];
let factions = [];

const upgrades = [
  {
    id: "clickMatrix",
    name: "Click Matrix",
    description: "Increases manual pulse energy and XP.",
    baseCost: 10,
    scale: 1.42,
    currency: "energy",
    effectText: level => `+${format(0.65 * level)} manual multiplier`,
    apply: level => 1 + level * 0.65
  },
  {
    id: "droneSwarm",
    name: "Drone Swarm",
    description: "Adds autonomous energy every second.",
    baseCost: 55,
    scale: 1.5,
    currency: "energy",
    effectText: level => `${level} drones online`,
    apply: level => level
  },
  {
    id: "coolantLoop",
    name: "Coolant Loop",
    description: "Reduces heat generated by clicks and drones.",
    baseCost: 25,
    scale: 1.55,
    currency: "credits",
    effectText: level => `${format(level * 4)}% heat damping`,
    apply: level => Math.min(0.65, level * 0.04)
  },
  {
    id: "serverCore",
    name: "Server Core",
    description: "Multiplies all passive production.",
    baseCost: 140,
    scale: 1.65,
    currency: "energy",
    effectText: level => `x${format(1 + level * 0.18)} passive output`,
    apply: level => 1 + level * 0.18
  },
  {
    id: "packetForge",
    name: "Packet Forge",
    description: "Generates packets used to launch operations.",
    baseCost: 80,
    scale: 1.6,
    currency: "credits",
    effectText: level => `+${format(level * 0.35)}/s packets`,
    apply: level => level * 0.35
  }
];

const researchNodes = [
  {
    id: "quantumCache",
    name: "Quantum Cache",
    cost: 150,
    requires: [],
    description: "Unlocks memory compression for a permanent +15% energy gain."
  },
  {
    id: "thermalAI",
    name: "Thermal AI",
    cost: 280,
    requires: ["quantumCache"],
    description: "Stability regenerates faster and heat decays harder."
  },
  {
    id: "botnetDiplomacy",
    name: "Botnet Diplomacy",
    cost: 420,
    requires: ["quantumCache"],
    description: "Faction bonuses include rival bot contributions."
  },
  {
    id: "singularityProtocol",
    name: "Singularity Protocol",
    cost: 900,
    requires: ["thermalAI", "botnetDiplomacy"],
    description: "Prestige multiplier scales from completed operations."
  }
];

const operations = [
  {
    id: "dataHeist",
    name: "Data Heist",
    packetCost: 25,
    duration: 18,
    heat: 16,
    reward: () => ({ credits: 90 + state.level * 12, xp: 60 }),
    description: "Steal encrypted credits from a rival shard."
  },
  {
    id: "coreOverclock",
    name: "Core Overclock",
    packetCost: 60,
    duration: 30,
    heat: 30,
    reward: () => ({ energy: 500 + energyPerSecond() * 45, xp: 120 }),
    description: "Risk heat spikes for a major energy injection."
  },
  {
    id: "factionRaid",
    name: "Faction Raid",
    packetCost: 110,
    duration: 45,
    heat: 45,
    reward: () => ({ credits: 350, energy: 900, xp: 220 }),
    description: "Coordinate with your faction to raid a boss node."
  }
];

const achievementRules = [
  { id: "firstPulse", name: "First Pulse", test: () => state.totalClicks >= 1 },
  { id: "hundredClicks", name: "100 Clicks", test: () => state.totalClicks >= 100 },
  { id: "levelTen", name: "Level 10", test: () => state.level >= 10 },
  { id: "operator", name: "Operator", test: () => totalOperationCompletions() >= 1 },
  { id: "researcher", name: "Researcher", test: () => Object.keys(state.research).length >= 2 },
  { id: "overlord", name: "Overlord", test: () => state.prestige >= 1 }
];

const elements = {
  clickCore: document.getElementById("click-core"),
  pulseGain: document.getElementById("pulse-gain"),
  energyDisplay: document.getElementById("energy-display"),
  creditsDisplay: document.getElementById("credits-display"),
  levelDisplay: document.getElementById("level-display"),
  heatDisplay: document.getElementById("heat-display"),
  stabilityDisplay: document.getElementById("stability-display"),
  ascensionDisplay: document.getElementById("ascension-display"),
  energyRate: document.getElementById("energy-rate"),
  creditRate: document.getElementById("credit-rate"),
  botPressure: document.getElementById("bot-pressure"),
  xpFill: document.getElementById("xp-fill"),
  xpText: document.getElementById("xp-text"),
  eventLog: document.getElementById("event-log"),
  resetSave: document.getElementById("reset-save")
};

function format(value) {
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(2)}M`;
  if (value >= 10_000) return `${(value / 1_000).toFixed(1)}K`;
  if (value >= 1000) return Math.floor(value).toLocaleString();
  if (value % 1 !== 0 && value < 100) return value.toFixed(1);
  return Math.floor(value).toLocaleString();
}

function upgradeLevel(id) {
  return state.upgradeLevels[id] || 0;
}

function upgradeCost(upgrade) {
  const level = upgradeLevel(upgrade.id);
  const researchDiscount = state.research.quantumCache ? 0.92 : 1;
  return Math.floor(upgrade.baseCost * upgrade.scale ** level * researchDiscount);
}

function canAfford(currency, amount) {
  return state[currency] >= amount;
}

function manualGain() {
  const clickUpgrade = upgrades.find(upgrade => upgrade.id === "clickMatrix");
  const cacheBonus = state.research.quantumCache ? 1.15 : 1;
  const prestigeBonus = 1 + state.prestige * 0.35 + state.rebirths * 0.12;
  const operationBonus = state.research.singularityProtocol ? 1 + totalOperationCompletions() * 0.02 : 1;
  return state.multiplier * clickUpgrade.apply(upgradeLevel("clickMatrix")) * cacheBonus * prestigeBonus * operationBonus;
}

function heatDamping() {
  const coolant = upgrades.find(upgrade => upgrade.id === "coolantLoop");
  return coolant.apply(upgradeLevel("coolantLoop"));
}

function passiveMultiplier() {
  const serverCore = upgrades.find(upgrade => upgrade.id === "serverCore");
  return serverCore.apply(upgradeLevel("serverCore")) * (1 + state.cores * 0.04);
}

function energyPerSecond() {
  const droneOutput = upgradeLevel("droneSwarm") * 0.8;
  const stabilityPenalty = Math.max(0.25, state.stability / 100);
  return droneOutput * passiveMultiplier() * stabilityPenalty * (state.research.quantumCache ? 1.15 : 1);
}

function creditsPerSecond() {
  return energyPerSecond() * 0.16 * state.market.creditValue;
}

function packetsPerSecond() {
  const packetForge = upgrades.find(upgrade => upgrade.id === "packetForge");
  return packetForge.apply(upgradeLevel("packetForge")) * (state.research.botnetDiplomacy ? 1.25 : 1);
}

function totalOperationCompletions() {
  return Object.values(state.operationCompletions).reduce((sum, count) => sum + count, 0);
}

function addEvent(message, tone = "info") {
  state.eventLog.unshift({ message, tone, time: new Date().toLocaleTimeString() });
  state.eventLog = state.eventLog.slice(0, 10);
  renderEventLog();
}

function initBots(count = BOT_COUNT) {
  const personalities = ["Grindy", "Casual", "Lazy", "Strategic", "Raider"];
  bots = Array.from({ length: count }, (_, index) => ({
    name: `Bot${index + 1}`,
    energy: Math.floor(Math.random() * 1000),
    level: Math.floor(Math.random() * 5) + 1,
    xp: Math.floor(Math.random() * 50),
    rebirths: 0,
    prestige: 0,
    personality: personalities[Math.floor(Math.random() * personalities.length)],
    faction: null
  }));
}

function initFactions() {
  factions = ["Neon Syndicate", "Chrome Garden", "Ghost Relay", "Solar Null"].map((name, index) => ({
    name,
    members: bots.slice(index * 20, index * 20 + 20),
    energy: 0,
    doctrine: ["Aggressive", "Economic", "Defensive", "Research"][index]
  }));
  factions.forEach(faction => faction.members.forEach(bot => { bot.faction = faction.name; }));
}

function pulseCore() {
  const gain = manualGain();
  const heatGain = Math.max(0.2, 1.8 * (1 - heatDamping()));
  state.energy += gain;
  state.xp += gain;
  state.heat = Math.min(100, state.heat + heatGain);
  state.totalClicks += 1;
  if (state.heat > 85) state.stability = Math.max(20, state.stability - 2.5);
  checkLevelUp();
  checkAchievements();
  updateUI();
}

function checkLevelUp() {
  let leveled = false;
  while (state.xp >= state.xpNeeded) {
    state.xp -= state.xpNeeded;
    state.level += 1;
    state.xpNeeded = Math.floor(state.xpNeeded * 1.13 + 25);
    state.credits += 20 + state.level * 4;
    leveled = true;
  }
  if (leveled) addEvent(`Level ${state.level} reached. Bonus credits deposited.`, "success");
}

function buyUpgrade(id) {
  const upgrade = upgrades.find(item => item.id === id);
  const cost = upgradeCost(upgrade);
  if (!canAfford(upgrade.currency, cost)) return;
  state[upgrade.currency] -= cost;
  state.upgradeLevels[id] = upgradeLevel(id) + 1;
  state.drones = upgradeLevel("droneSwarm");
  addEvent(`${upgrade.name} upgraded to level ${upgradeLevel(id)}.`, "success");
  renderCurrentTab();
  updateUI();
}

function canResearch(node) {
  return !state.research[node.id] && node.requires.every(id => state.research[id]) && state.credits >= node.cost;
}

function buyResearch(id) {
  const node = researchNodes.find(item => item.id === id);
  if (!canResearch(node)) return;
  state.credits -= node.cost;
  state.research[id] = true;
  addEvent(`${node.name} research completed.`, "success");
  renderCurrentTab();
  updateUI();
}

function startOperation(id) {
  const operation = operations.find(item => item.id === id);
  if (state.activeOperationId || state.packets < operation.packetCost) return;
  state.packets -= operation.packetCost;
  state.activeOperationId = id;
  state.operationProgress = 0;
  state.heat = Math.min(100, state.heat + operation.heat);
  addEvent(`${operation.name} started. Heat spike detected.`, "warning");
  renderCurrentTab();
  updateUI();
}

function finishOperation(operation) {
  const reward = operation.reward();
  state.energy += reward.energy || 0;
  state.credits += reward.credits || 0;
  state.xp += reward.xp || 0;
  state.operationCompletions[operation.id] = (state.operationCompletions[operation.id] || 0) + 1;
  state.activeOperationId = null;
  state.operationProgress = 0;
  addEvent(`${operation.name} complete: +${format(reward.energy || 0)} energy, +${format(reward.credits || 0)} credits.`, "success");
  checkLevelUp();
  checkAchievements();
}

function rebirthGame() {
  if (state.level < 25) return;
  state.rebirths += 1;
  state.multiplier += 0.5;
  softReset("Rebirth complete. Manual systems permanently amplified.");
}

function prestigeGame() {
  if (state.level < 50) return;
  state.prestige += 1;
  state.multiplier += 1 + state.prestige * 0.2;
  state.cores += 1;
  softReset("Prestige complete. A new server core has awakened.");
}

function softReset(message) {
  state.energy = 0;
  state.credits = 0;
  state.xp = 0;
  state.level = 1;
  state.xpNeeded = 100;
  state.heat = 0;
  state.stability = 100;
  state.packets = 0;
  state.activeOperationId = null;
  state.operationProgress = 0;
  addEvent(message, "success");
  renderCurrentTab();
  updateUI();
  saveGame();
}

function gameTick() {
  state.energy += energyPerSecond();
  state.credits += creditsPerSecond();
  state.packets += packetsPerSecond();
  state.xp += energyPerSecond() * 0.25;

  const heatDecay = state.research.thermalAI ? 7 : 4;
  state.heat = Math.max(0, state.heat - heatDecay * (1 + heatDamping() / 2));
  if (state.heat < 55) state.stability = Math.min(100, state.stability + (state.research.thermalAI ? 3.5 : 2));
  if (state.heat > 90) state.stability = Math.max(15, state.stability - 4);

  if (state.activeOperationId) {
    const operation = operations.find(item => item.id === state.activeOperationId);
    state.operationProgress += 1;
    if (state.operationProgress >= operation.duration) finishOperation(operation);
  }

  tickMarket();
  checkLevelUp();
  checkAchievements();
  renderCurrentTab();
  updateUI();
}

function tickMarket() {
  const roll = Math.random();
  if (roll < 0.08) {
    const direction = Math.random() > 0.5 ? 1 : -1;
    state.market.creditValue = Math.min(1.8, Math.max(0.55, state.market.creditValue + direction * state.market.volatility));
    state.market.phase = direction > 0 ? "bullish" : "bearish";
  }
  if (roll > 0.985) {
    const bonus = Math.floor(40 + Math.random() * 120 + state.level * 6);
    state.credits += bonus;
    addEvent(`Market anomaly converted ghost traffic into ${bonus} credits.`, "success");
  }
}

function tickBots() {
  bots.forEach(bot => {
    const aggression = bot.personality === "Raider" ? 1.8 : bot.personality === "Strategic" ? 1.35 : 1;
    const gain = (Math.random() + 0.5) * aggression * (1 + bot.prestige * 0.2);
    bot.energy += gain;
    bot.xp += gain;
    while (bot.xp >= 50 + bot.level * 5) {
      bot.xp -= 50 + bot.level * 5;
      bot.level += 1;
    }
    if (bot.level >= 25 && Math.random() < 0.004) {
      bot.level = 1;
      bot.rebirths += 1;
    }
    if (bot.level >= 50 && Math.random() < 0.002) {
      bot.level = 1;
      bot.prestige += 1;
    }
  });
  updateFactionEnergy();
  if (state.currentTab === "leaderboard" || state.currentTab === "factions") renderCurrentTab();
}

function updateFactionEnergy() {
  factions.forEach(faction => {
    const botEnergy = faction.members.reduce((sum, member) => sum + (member.energy || 0), 0);
    const diplomacyBonus = state.research.botnetDiplomacy ? state.energy * 0.1 : 0;
    faction.energy = botEnergy + diplomacyBonus;
  });
}

function checkAchievements() {
  achievementRules.forEach(rule => {
    if (!state.achievements.includes(rule.id) && rule.test()) {
      state.achievements.push(rule.id);
      addEvent(`Achievement unlocked: ${rule.name}.`, "success");
    }
  });
}

function renderCurrentTab() {
  renderTab(state.currentTab);
}

function renderTab(tab) {
  const container = document.getElementById(tab);
  if (!container) return;

  if (tab === "upgrades") {
    container.innerHTML = upgrades.map(upgrade => {
      const level = upgradeLevel(upgrade.id);
      const cost = upgradeCost(upgrade);
      const disabled = canAfford(upgrade.currency, cost) ? "" : "disabled";
      return `<article class="system-card">
        <div><h3>${upgrade.name} <span>Lvl ${level}</span></h3><p>${upgrade.description}</p><small>${upgrade.effectText(level)}</small></div>
        <button ${disabled} onclick="buyUpgrade('${upgrade.id}')">Buy · ${format(cost)} ${upgrade.currency}</button>
      </article>`;
    }).join("");
  }

  if (tab === "research") {
    container.innerHTML = researchNodes.map(node => {
      const complete = state.research[node.id];
      const locked = !node.requires.every(id => state.research[id]);
      const disabled = complete || locked || state.credits < node.cost ? "disabled" : "";
      const status = complete ? "Complete" : locked ? `Requires ${node.requires.join(", ")}` : `${format(node.cost)} credits`;
      return `<article class="system-card ${complete ? "complete" : ""}">
        <div><h3>${node.name}</h3><p>${node.description}</p><small>${status}</small></div>
        <button ${disabled} onclick="buyResearch('${node.id}')">Research</button>
      </article>`;
    }).join("");
  }

  if (tab === "operations") {
    container.innerHTML = operations.map(operation => {
      const active = state.activeOperationId === operation.id;
      const disabled = state.activeOperationId || state.packets < operation.packetCost ? "disabled" : "";
      const progress = active ? Math.floor((state.operationProgress / operation.duration) * 100) : 0;
      return `<article class="system-card operation-card">
        <div><h3>${operation.name}</h3><p>${operation.description}</p><small>${format(operation.packetCost)} packets · ${operation.duration}s · +${operation.heat}% heat</small>
        <div class="mini-bar"><span style="width:${progress}%"></span></div></div>
        <button ${disabled} onclick="startOperation('${operation.id}')">${active ? `${progress}%` : "Launch"}</button>
      </article>`;
    }).join("") + `<div class="ascension-actions"><button onclick="rebirthGame()" ${state.level >= 25 ? "" : "disabled"}>Rebirth at level 25</button><button onclick="prestigeGame()" ${state.level >= 50 ? "" : "disabled"}>Prestige at level 50</button></div>`;
  }

  if (tab === "leaderboard") {
    const sorted = [...bots, { name: "You", energy: state.energy, level: state.level, prestige: state.prestige }]
      .sort((a, b) => b.energy - a.energy)
      .slice(0, 12);
    container.innerHTML = `<ol class="rank-list">${sorted.map((player, index) => `<li><strong>#${index + 1} ${player.name}</strong><span>${format(player.energy)} energy · Lvl ${player.level}</span></li>`).join("")}</ol>`;
  }

  if (tab === "factions") {
    updateFactionEnergy();
    container.innerHTML = `<div class="faction-grid">${factions.map(faction => `<article class="system-card">
      <div><h3>${faction.name}</h3><p>${faction.doctrine} doctrine · ${faction.members.length} rivals</p><small>${format(faction.energy)} combined energy</small></div>
    </article>`).join("")}</div>`;
  }

  if (tab === "stats") {
    container.innerHTML = `<div class="stats-grid">
      <p><span>Total Clicks</span><strong>${format(state.totalClicks)}</strong></p>
      <p><span>Energy/sec</span><strong>${format(energyPerSecond())}</strong></p>
      <p><span>Credits/sec</span><strong>${format(creditsPerSecond())}</strong></p>
      <p><span>Packets/sec</span><strong>${format(packetsPerSecond())}</strong></p>
      <p><span>Market</span><strong>${state.market.phase} x${state.market.creditValue.toFixed(2)}</strong></p>
      <p><span>Operations Won</span><strong>${totalOperationCompletions()}</strong></p>
    </div>`;
  }

  if (tab === "achievements") {
    container.innerHTML = `<ul class="achievement-list">${achievementRules.map(rule => `<li class="${state.achievements.includes(rule.id) ? "unlocked" : ""}"><strong>${rule.name}</strong><span>${state.achievements.includes(rule.id) ? "Unlocked" : "Locked"}</span></li>`).join("")}</ul>`;
  }
}

function renderEventLog() {
  elements.eventLog.innerHTML = state.eventLog.map(event => `<li class="${event.tone}"><span>${event.time}</span>${event.message}</li>`).join("");
}

function updateUI() {
  elements.energyDisplay.textContent = format(state.energy);
  elements.creditsDisplay.textContent = format(state.credits);
  elements.levelDisplay.textContent = state.level;
  elements.heatDisplay.textContent = `${Math.round(state.heat)}%`;
  elements.stabilityDisplay.textContent = `${Math.round(state.stability)}%`;
  elements.ascensionDisplay.textContent = `${state.rebirths} / ${state.prestige}`;
  elements.pulseGain.textContent = `+${format(manualGain())} energy`;
  elements.energyRate.textContent = `+${format(energyPerSecond())}/s energy`;
  elements.creditRate.textContent = `+${format(creditsPerSecond())}/s credits · +${format(packetsPerSecond())}/s packets`;
  elements.botPressure.textContent = `${bots.length} rivals online`;
  const xpPercent = Math.min(100, (state.xp / state.xpNeeded) * 100);
  elements.xpFill.style.width = `${xpPercent}%`;
  elements.xpText.textContent = `XP: ${format(state.xp)} / ${format(state.xpNeeded)}`;
}

function saveGame() {
  localStorage.setItem(SAVE_KEY, JSON.stringify(state));
}

function loadGame() {
  const saved = localStorage.getItem(SAVE_KEY);
  if (!saved) return;
  const parsed = JSON.parse(saved);
  state = { ...structuredClone(defaultState), ...parsed };
  state.market = { ...defaultState.market, ...(parsed.market || {}) };
}

function resetGame() {
  localStorage.removeItem(SAVE_KEY);
  state = structuredClone(defaultState);
  syncActiveTab();
  addEvent("Simulation reset. A clean empire seed is ready.", "warning");
  renderCurrentTab();
  updateUI();
}

function syncActiveTab() {
  document.querySelectorAll(".tab-btn").forEach(button => {
    button.classList.toggle("active", button.dataset.tab === state.currentTab);
  });
  document.querySelectorAll(".tab-content").forEach(content => {
    content.classList.toggle("active", content.id === state.currentTab);
  });
}

document.querySelectorAll(".tab-btn").forEach(tab => {
  tab.addEventListener("click", () => {
    document.querySelectorAll(".tab-btn").forEach(button => button.classList.remove("active"));
    document.querySelectorAll(".tab-content").forEach(content => content.classList.remove("active"));
    tab.classList.add("active");
    document.getElementById(tab.dataset.tab).classList.add("active");
    state.currentTab = tab.dataset.tab;
    renderCurrentTab();
  });
});

elements.clickCore.addEventListener("click", pulseCore);
elements.resetSave.addEventListener("click", resetGame);

loadGame();
syncActiveTab();
initBots();
initFactions();
if (!state.eventLog.length) addEvent("Neural empire booted. Pulse the core to begin.", "info");
renderEventLog();
renderCurrentTab();
updateUI();
setInterval(gameTick, TICK_MS);
setInterval(tickBots, 2000);
setInterval(saveGame, 1000);
